[DB Migration] Fix undesired column names
gnosis/gp-v2-services pull request #914
Opened 2021-07-29 16:33 UTC by bh2smith

The recent merge of #906 and #908 introduced undesired column names to the DB while also making a gap in the flyaway DB migration script file naming convention (using V011 instead of V010 - this happened to make room for #875, which will not likely be merged before this).

Game plan for tomorrow is to revert both of the PRs mentioned above, restore staging DB from backup and then merge this as the corrected culmination of both.

Note that - the visable diff with main at this moment just shows the changes after the two branches are merged, but once they are reverted this should appear as all the code required to make the changes introduced in the above to PRs.

2021-07-29 17:25 UTC, bh2smith commented
@nlordell - after some discussion with @alfetopito I think a more appropriate name for these types, fields and columns might be something like:

```
SellTokenSource & BuyTokenDest
```

WDYT?

2021-07-29 18:43 UTC, nlordell commented
I think that the field and column names should be `sell_token_balance` and `buy_token_balance` because that is what they are in the SC and what is signed in the order. It would be quite weird if the FE would sign some order JSON data, and then have to rename just these two properites to send to the API. Also, I feel like it causes confusion.

If we want to rename the order field names/enum values (`erc20`, `internal`, `external`) I think we should also do it in the SC and re-deploy. I think we should have that conversation here: https://github.com/gnosis/gp-v2-contracts/issues/543.

As for the enum type names, I like it!

2021-07-30 12:14 UTC, vkgnosis approved these changes

2021-07-30 12:38 UTC, nlordell commented on database/sql/V010__skipped.sql
> +-- V010 was accidentally skipped, this empty placeholder file is just placed here
flyway will not allow this.

2021-07-30 12:39 UTC, nlordell requested changes
Did you try the migration locally? When I tried editing previous migration scripts (even if it was to just to change a comment) the migration failed.

2021-07-30 12:44 UTC, bh2smith commented
> Did you try the migration locally? When I tried editing previous migration scripts (even if it was to just to change a comment) the migration failed.

I am trying to do it locally now, but something isn't working and the errors I am getting in the front end are not being propagated properly in the backend. I have a fresh DB and the interface keeps giving me an "Order not found error"

2021-07-30 13:00 UTC, bh2smith commented
@nlordell - Unfortunately the problem is that I tried to edit the V010 file (fixing a typo) and the checksum doesn't match. Loks like we will live with the typo forever.

```
ERROR: Validate failed: Migrations have failed validation
Migration checksum mismatch for migration version 010
-> Applied to database : 792685460
-> Resolved locally    : -1394922178. Either revert the changes to the migration, or run repair to update the schema history.
```

2021-07-30 13:07 UTC, bh2smith commented
@nlordell - testplan has been included above and I have run it locally as well. The problem you had was with the typo I tried to fix in V010.

2021-07-30 14:18 UTC, nlordell commented
Should the OpenAPI YAML need to be updated with the new names as well?

2021-07-30 14:55 UTC, taminomara commented
I wonder if we can just roll back staging and make a clean upgrade file without amends?

2021-07-30 15:00 UTC, bh2smith commented
> I wonder if we can just roll back staging and make a clean upgrade file without amends?

We tried this but undo is not available with the community version of flyaway.

2021-07-30 20:14 UTC, bh2smith commented
changes ready for review.

2021-08-02 05:59 UTC, nlordell approved these changes

2021-08-02 12:56 UTC, merged